### ISSUE TITLE
Error in using emotion-anew plugin

### ISSUE THREAD

**Issue by finarb** [gsi-upm/senpy-plugins-community#11]
on using the command

`senpy -f senpy-plugins-community`

i get the following traceback

```
WARNING:senpy.plugins:GSITK is not installed. Some functions will be unavailable.
WARNING:senpy.extensions:GSITK is not installed. Some functions will be unavailable.
WARNING:senpy.plugins:Plugin DaedalusPlugin does not have a description. Please, add a short summary to help other developers
WARNING:senpy.plugins:Plugin ExamplePlugin does not have a description. Please, add a short summary to help other developers
WARNING:senpy.plugins:Plugin EmotionTextPlugin does not have a description. Please, add a short summary to help other developers
WARNING:senpy.plugins:Plugin SentiTextPlugin does not have a description. Please, add a short summary to help other developers
WARNING:senpy.plugins:Plugin vaderSentimentPlugin does not have a description. Please, add a short summary to help other developers
WARNING:senpy.plugins:Plugin Sentiment140Plugin does not have a description. Please, add a short summary to help other developers
WARNING:senpy.plugins:Plugin EmotionTextPlugin does not have a description. Please, add a short summary to help other developers
WARNING:senpy.plugins:Overloading plugin class: EmotionTextPlugin
WARNING:senpy.plugins:Plugin unifiedPlugin does not have a description. Please, add a short summary to help other developers
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/abhishekray/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/abhishekray/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/abhishekray/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
Traceback (most recent call last):
  File "/usr/local/bin/senpy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/senpy/__main__.py", line 131, in main
    sp.activate_all()
  File "/usr/local/lib/python2.7/site-packages/senpy/extensions.py", line 324, in activate_all
    ps.append(self.activate_plugin(plug, sync=sync))
  File "/usr/local/lib/python2.7/site-packages/senpy/extensions.py", line 360, in activate_plugin
    self._activate(plugin)
  File "/usr/local/lib/python2.7/site-packages/senpy/extensions.py", line 344, in _activate
    plugin.activate()
  File "senpy-plugins-community/emotion-wnaffect/emotion-wnaffect.py", line 85, in activate
    self._load_emotions(local_path + self.hierarchy_path)
  File "senpy-plugins-community/emotion-wnaffect/emotion-wnaffect.py", line 50, in _load_emotions
    Emo.emotions[name] = Emo(name, elem.get("isa"))
  File "senpy-plugins-community/emotion-wnaffect/emotion.py", line 24, in __init__
    self.parent = Emotion.emotions[parent_name] if parent_name else None
KeyError: 'sympathy'
```

**Comment by balkian** [comment]
Your problem is actually with sentiment-wnaffect.
Have you by chance created an empty a-hierarchy.xml file? That would explain the situation.

Could you please update the repository and try again?

We have included a docker-compose file for convenience, and a senpy option `--allow-fail` so that plugins that fail to activate (due to missing data, mostly) will not prevent the server from running anymore.

**Comment by balkian** [comment]
I'm closing this issue. Feel free to re-open if the problem persists.
