### ISSUE TITLE
Exception activating emotion-wnaffect

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy-plugins-community#4]
```
ERROR:senpy.extensions:Error activating plugin emotion-wnaffect - 'sympathy' : 
	Traceback (most recent call last):
  File "/Users/drevicko/anaconda/envs/python2/lib/python2.7/site-packages/senpy/extensions.py", line 290, in act
    plugin.activate()
  File "./emotion-wnaffect/emotion-wnaffect.py", line 70, in activate
    self._load_emotions(self.hierarchy_path)
  File "./emotion-wnaffect/emotion-wnaffect.py", line 50, in _load_emotions
    Emo.emotions[name] = Emo(name, elem.get("isa"))
  File "./emotion-wnaffect/emotion.py", line 25, in __init__
    self.parent = Emotion.emotions[parent_name] if parent_name else None
KeyError: 'sympathy'
```

I've senpy 0.8.7 running in anaconda python 2.7 and wn-affect-1.1 files in /data/emotion-wnaffect (actually the folder is a link, but I don't think that's the problem).

**Comment by drevicko** [comment]
It seems there's a typo in wn-affect-1.1/a-hierarchy.xml:

  <categ name="simpathy" isa="liking"/>

should be

  <categ name="sympathy" isa="liking"/>
